export type WolofWord = {
  french: string;
  wolof: string;
  phonetic: string;
  example?: string;
  exampleTranslation?: string;
};

export type Lesson = {
  id: string;
  title: string;
  description: string;
  emoji: string;
  color: string;
  bgColor: string;
  words: WolofWord[];
};

export const lessons: Lesson[] = [
  {
    id: "alphabet",
    title: "L'Alphabet",
    description: "Les lettres et sons du wolof",
    emoji: "🔤",
    color: "#FFCF86",
    bgColor: "#FFF3E0",
    words: [
      { french: "Lettre A", wolof: "A", phonetic: "a comme dans 'ba' (père)" },
      { french: "Lettre B", wolof: "B", phonetic: "b comme en français" },
      { french: "Lettre C", wolof: "C", phonetic: "toujours 'tch', jamais 's' ni 'k' — ex : ceeb (riz)" },
      { french: "Lettre D", wolof: "D", phonetic: "d comme en français" },
      { french: "Lettre E", wolof: "E", phonetic: "e ouvert, comme dans 'bec'" },
      { french: "Lettre É", wolof: "É", phonetic: "e fermé, comme dans 'blé'" },
      { french: "Lettre F", wolof: "F", phonetic: "f comme en français" },
      { french: "Lettre G", wolof: "G", phonetic: "toujours dur, comme dans 'gare' — jamais comme 'j'" },
      { french: "Lettre I", wolof: "I", phonetic: "i comme dans 'ici'" },
      { french: "Lettre J", wolof: "J", phonetic: "comme 'dj' anglais (join) — ex : jënd (acheter)" },
      { french: "Lettre K", wolof: "K", phonetic: "k comme en français" },
      { french: "Lettre L", wolof: "L", phonetic: "l comme en français" },
      { french: "Lettre M", wolof: "M", phonetic: "m comme en français" },
      { french: "Lettre N", wolof: "N", phonetic: "n comme en français" },
      { french: "Lettre Ñ", wolof: "Ñ", phonetic: "comme le 'gn' de 'montagne' — ex : ñam (nourriture)" },
      { french: "Lettre Ŋ", wolof: "Ŋ", phonetic: "souvent noté 'ng', son nasal vélaire, comme 'ng' de 'parking' — ex : ŋoon (soir)" },
      { french: "Lettre O", wolof: "O", phonetic: "o ouvert, comme dans 'porte'" },
      { french: "Lettre Ó", wolof: "Ó", phonetic: "o fermé, comme dans 'pot'" },
      { french: "Lettre P", wolof: "P", phonetic: "p comme en français" },
      { french: "Lettre Q", wolof: "Q", phonetic: "rare, emprunts arabes surtout" },
      { french: "Lettre R", wolof: "R", phonetic: "roulé, comme en espagnol" },
      { french: "Lettre S", wolof: "S", phonetic: "toujours 's' dur, jamais 'z'" },
      { french: "Lettre T", wolof: "T", phonetic: "t comme en français" },
      { french: "Lettre U", wolof: "U", phonetic: "comme 'ou' français — ex : nuur (couleur)" },
      { french: "Lettre W", wolof: "W", phonetic: "comme en anglais 'w' — ex : waaw (oui)" },
      { french: "Lettre X", wolof: "X", phonetic: "son guttural, proche du 'ch' allemand ou espagnol jota — ex : xale (enfant)" },
      { french: "Lettre Y", wolof: "Y", phonetic: "y comme en français" },
    ],
  },
  {
    id: "salutations",
    title: "Salutations",
    description: "Les salutations et formules de politesse",
    emoji: "👋",
    color: "#FF6B6B",
    bgColor: "#FFE8E8",
    words: [
      { french: "Bonjour (salutation la plus courante)", wolof: "Asalaamaalekum", phonetic: "asalaamaalekoum" },
      { french: "Réponse à « Asalaamaalekum »", wolof: "Maalekum salaam", phonetic: "maalekoum salaam" },
      { french: "Comment vas-tu ?", wolof: "Nanga def", phonetic: "nanga def" },
      { french: "Je vais bien (litt. je suis ici)", wolof: "Mangi fi", phonetic: "mangi fi" },
      { french: "Comment t'appelles-tu ?", wolof: "Naka nga tudd", phonetic: "naka nga toudd" },
      { french: "Je m'appelle...", wolof: "Maa ngi tudd...", phonetic: "maa ngi toudd..." },
      { french: "À la prochaine fois", wolof: "Ba beneen yoon", phonetic: "ba benéén yoon" },
      { french: "À demain", wolof: "Ba suba", phonetic: "ba souba" },
      { french: "Merci", wolof: "Jërejëf", phonetic: "djeuredjeuf" },
      { french: "Il n'y a pas de quoi / de rien", wolof: "Amul solo", phonetic: "amoul solo" },
      { french: "Excuse-moi / pardonne-moi", wolof: "Baal ma", phonetic: "baal ma" },
      { french: "Oui", wolof: "Waaw", phonetic: "waaw" },
      { french: "Non", wolof: "Déedéet", phonetic: "déedéet" },
      { french: "Remercier", wolof: "Sant", phonetic: "sant" },
      { french: "Bienvenue (litt. installe-toi en paix)", wolof: "Dalal ak jamm", phonetic: "dalal ak djamm" },
      { french: "Tout va bien (litt. paix seulement)", wolof: "Jamm rekk", phonetic: "djamm rekk" },
      { french: "Comment va la famille ?", wolof: "Naka waa kër ga", phonetic: "naka waa keur ga" },
      { french: "Ils vont bien / ils sont là", wolof: "Ñu ngi fi", phonetic: "gnou ngi fi" },
      { french: "D'où viens-tu ?", wolof: "Foo jogé", phonetic: "foo djogé" },
      { french: "Moi, je... (pour se présenter)", wolof: "Man...", phonetic: "man..." },
    ],
  },
  {
    id: "expressions",
    title: "Expressions Courantes",
    description: "Des phrases utiles pour la vie de tous les jours",
    emoji: "💬",
    color: "#6BCB77",
    bgColor: "#E8FFE9",
    words: [
      { french: "Comment vas-tu ?", wolof: "Nanga def ?", phonetic: "nanga def ?" },
      { french: "Je vais bien, tout simplement", wolof: "Mangi fi rekk", phonetic: "mangi fi rekk" },
      { french: "Comment va la famille ?", wolof: "Ana waa kër ga ?", phonetic: "ana waa keur ga ?" },
      { french: "Merci mais...", wolof: "Jërejëf waaye", phonetic: "djeuredjeuf waaye" },
      { french: "Si Dieu le veut", wolof: "Su ëllëgee", phonetic: "sou eulleugéé" },
      { french: "Excuse-moi car...", wolof: "Baal ma ndax...", phonetic: "baal ma ndakh..." },
      { french: "Où vas-tu ?", wolof: "Foo jëm ?", phonetic: "foo djeum ?" },
      { french: "Je m'en vais", wolof: "Damay dem", phonetic: "damay dem" },
      { french: "Comment vont les gens ?", wolof: "Naka gaa ngi ?", phonetic: "naka gaa ngi ?" },
      { french: "Est-ce que tu... ?", wolof: "Xanaa dangaa..?", phonetic: "khanaa dangaa..?" },
      { french: "Si jamais... / au cas où...", wolof: "Su fekkee...", phonetic: "sou fekkéé..." },
      { french: "J'ai envie de manger", wolof: "Dama bëgga lekk", phonetic: "dama beugga lekk" },
      { french: "Je suis fatigué(e)", wolof: "Dama sonn", phonetic: "dama sonn" },
      { french: "J'ai faim", wolof: "Dama xiif", phonetic: "dama khiif" },
      { french: "J'ai soif", wolof: "Dama mar", phonetic: "dama mar" },
      { french: "Où habites-tu ?", wolof: "Fan nga dëkk ?", phonetic: "fan nga deukk ?" },
      { french: "Moi, j'habite à...", wolof: "Man dama dëkk ci...", phonetic: "man dama deukk tchi..." },
      { french: "Combien ça coûte ?", wolof: "Ñaata la ?", phonetic: "gnaata la ?" },
      { french: "Je voudrais acheter...", wolof: "Dama bëgga jënd...", phonetic: "dama beugga djeund..." },
      { french: "Si tu veux bien / s'il te plaît", wolof: "Su ko neexee", phonetic: "sou ko néékhéé" },
      { french: "Je te fais confiance", wolof: "Wóolu naa la", phonetic: "woolou naa la" },
      { french: "Tout de suite", wolof: "Léegi léegi", phonetic: "léegi léegi" },
      { french: "À plus tard", wolof: "Ba beneen", phonetic: "ba benéén" },
      { french: "Que Dieu t'accorde la paix", wolof: "Yàlla na la may jamm", phonetic: "yàlla na la may djamm" },
      { french: "Ne t'inquiète pas (litt. il n'a rien fait)", wolof: "Deful dara", phonetic: "defoul dara" },
      { french: "Tu sais ? / Tu comprends ?", wolof: "Xam nga ?", phonetic: "kham nga ?" },
      { french: "Oui, je sais", wolof: "Waaw, xam naa", phonetic: "waaw, kham naa" },
      { french: "Non, je ne sais pas", wolof: "Déedéet, xamuma", phonetic: "déedéet, khamouma" },
    ],
  },
  {
    id: "pronoms",
    title: "Les Pronoms",
    description: "Pronoms sujets et possessifs de base",
    emoji: "🗣️",
    color: "#D9B3FF",
    bgColor: "#F3E8FF",
    words: [
      { french: "Moi / je", wolof: "Man", phonetic: "man" },
      { french: "Toi / tu", wolof: "Yow", phonetic: "yow" },
      { french: "Lui / elle", wolof: "Moom", phonetic: "moom" },
      { french: "Nous", wolof: "Ñun", phonetic: "gnoun" },
      { french: "Vous", wolof: "Yéen", phonetic: "yéen" },
      { french: "Eux / elles", wolof: "Ñoom", phonetic: "gnoom" },
      { french: "Mon / ma", wolof: "Sama", phonetic: "sama" },
      { french: "Ton / ta", wolof: "Sa", phonetic: "sa" },
      { french: "Notre", wolof: "Sunu", phonetic: "sounou" },
      { french: "Votre / leur", wolof: "Seen", phonetic: "séén" },
    ],
  },
  {
    id: "famille",
    title: "La Famille",
    description: "Le vocabulaire de la famille",
    emoji: "👨‍👩‍👧‍👦",
    color: "#FFB3C6",
    bgColor: "#FFE8EE",
    words: [
      { french: "Maison / famille", wolof: "Kër", phonetic: "keur" },
      { french: "Père", wolof: "Baay", phonetic: "baay" },
      { french: "Mère", wolof: "Yaay", phonetic: "yaay" },
      { french: "Enfant (fils/fille)", wolof: "Doom", phonetic: "doom" },
      { french: "Épouse", wolof: "Jabar", phonetic: "djabar" },
      { french: "Époux", wolof: "Jëkkër", phonetic: "djeukkeur" },
      { french: "Aîné(e)", wolof: "Mag", phonetic: "mag" },
      { french: "Cadet(te)", wolof: "Rakk", phonetic: "rakk" },
      { french: "Grand-mère", wolof: "Mamdaam", phonetic: "mamdaam" },
      { french: "Grand-père (variante régionale)", wolof: "Mamdiop", phonetic: "mamdiop" },
      { french: "Oncle maternel", wolof: "Nijaay", phonetic: "nidjaay" },
      { french: "Tante paternelle", wolof: "Bàjjan", phonetic: "bàdjdjan" },
      { french: "Ami(e)", wolof: "Xarit", phonetic: "kharit" },
      { french: "Chef de famille", wolof: "Jëkkëru njaboot", phonetic: "djeukkeurou ndjaboot" },
      { french: "Famille (au sens large)", wolof: "Njaboot", phonetic: "ndjaboot" },
      { french: "Cousin(e)", wolof: "Sët", phonetic: "seut" },
      { french: "Homme / garçon", wolof: "Góor", phonetic: "goor" },
      { french: "Femme / fille", wolof: "Jigéen", phonetic: "djigéen" },
      { french: "Parents", wolof: "Waa jur", phonetic: "waa djour" },
      { french: "Accoucher / donner naissance", wolof: "Jur", phonetic: "djour" },
      { french: "Se marier", wolof: "Sey", phonetic: "sey" },
      { french: "Coépouse", wolof: "Nag", phonetic: "nag" },
      { french: "Marraine", wolof: "Ndeye ji", phonetic: "ndeye dji" },
      { french: "Parrain", wolof: "Baay ji", phonetic: "baay dji" },
      { french: "Nouveau-né", wolof: "Njël", phonetic: "ndjeul" },
    ],
  },
  {
    id: "chiffres",
    title: "Les Chiffres",
    description: "Compter en wolof",
    emoji: "🔢",
    color: "#4ECDC4",
    bgColor: "#E0FBF8",
    words: [
      { french: "0 / Zéro", wolof: "Tus", phonetic: "tous" },
      { french: "1", wolof: "Benn", phonetic: "benn" },
      { french: "2", wolof: "Ñaar", phonetic: "gnaar" },
      { french: "3", wolof: "Ñett", phonetic: "gnett" },
      { french: "4", wolof: "Ñeent", phonetic: "gnéént" },
      { french: "5", wolof: "Juróom", phonetic: "djouroom" },
      { french: "6", wolof: "Juróom-benn", phonetic: "djouroom-benn" },
      { french: "7", wolof: "Juróom-ñaar", phonetic: "djouroom-gnaar" },
      { french: "8", wolof: "Juróom-ñett", phonetic: "djouroom-gnett" },
      { french: "9", wolof: "Juróom-ñeent", phonetic: "djouroom-gnéént" },
      { french: "10", wolof: "Fukk", phonetic: "foukk" },
      { french: "11", wolof: "Fukk ak benn", phonetic: "foukk ak benn" },
      { french: "12", wolof: "Fukk ak ñaar", phonetic: "foukk ak gnaar" },
      { french: "13", wolof: "Fukk ak ñett", phonetic: "foukk ak gnett" },
      { french: "14", wolof: "Fukk ak ñeent", phonetic: "foukk ak gnéént" },
      { french: "15", wolof: "Fukk ak juróom", phonetic: "foukk ak djouroom" },
      { french: "16", wolof: "Fukk ak juróom-benn", phonetic: "foukk ak djouroom-benn" },
      { french: "17", wolof: "Fukk ak juróom-ñaar", phonetic: "foukk ak djouroom-gnaar" },
      { french: "18", wolof: "Fukk ak juróom-ñett", phonetic: "foukk ak djouroom-gnett" },
      { french: "19", wolof: "Fukk ak juróom-ñeent", phonetic: "foukk ak djouroom-gnéént" },
      { french: "20", wolof: "Ñaar-fukk", phonetic: "gnaar-foukk" },
      { french: "21", wolof: "Ñaar-fukk ak benn", phonetic: "gnaar-foukk ak benn" },
      { french: "22", wolof: "Ñaar-fukk ak ñaar", phonetic: "gnaar-foukk ak gnaar" },
      { french: "24", wolof: "Ñaar-fukk ak ñeent", phonetic: "gnaar-foukk ak gnéént" },
      { french: "25", wolof: "Ñaar-fukk ak juróom", phonetic: "gnaar-foukk ak djouroom" },
      { french: "30", wolof: "Ñett-fukk", phonetic: "gnett-foukk" },
      { french: "32", wolof: "Ñett-fukk ak ñaar", phonetic: "gnett-foukk ak gnaar" },
      { french: "33", wolof: "Ñett-fukk ak ñett", phonetic: "gnett-foukk ak gnett" },
      { french: "35", wolof: "Ñett-fukk ak juróom", phonetic: "gnett-foukk ak djouroom" },
      { french: "40", wolof: "Ñeent-fukk", phonetic: "gnéént-foukk" },
      { french: "44", wolof: "Ñeent-fukk ak ñeent", phonetic: "gnéént-foukk ak gnéént" },
      { french: "45", wolof: "Ñeent-fukk ak juróom", phonetic: "gnéént-foukk ak djouroom" },
      { french: "50", wolof: "Juróom-fukk", phonetic: "djouroom-foukk" },
      { french: "55", wolof: "Juróom-fukk ak juróom", phonetic: "djouroom-foukk ak djouroom" },
      { french: "60", wolof: "Juróom-benn fukk", phonetic: "djouroom-benn foukk" },
      { french: "70", wolof: "Juróom-ñaar fukk", phonetic: "djouroom-gnaar foukk" },
      { french: "80", wolof: "Juróom-ñett fukk", phonetic: "djouroom-gnett foukk" },
      { french: "90", wolof: "Juróom-ñeent fukk", phonetic: "djouroom-gnéént foukk" },
      { french: "99", wolof: "Juróom-ñeent fukk ak juróom-ñeent", phonetic: "djouroom-gnéént foukk ak djouroom-gnéént" },
      { french: "100", wolof: "Téeméer", phonetic: "téeméer" },
      { french: "200", wolof: "Ñaar téeméer", phonetic: "gnaar téeméer" },
      { french: "300", wolof: "Ñett téeméer", phonetic: "gnett téeméer" },
      { french: "500", wolof: "Juróom téeméer", phonetic: "djouroom téeméer" },
      { french: "1000", wolof: "Junni", phonetic: "djounni" },
      { french: "2000", wolof: "Ñaar junni", phonetic: "gnaar djounni" },
      { french: "Premier", wolof: "Njëkk", phonetic: "ndjeukk" },
      { french: "Deuxième", wolof: "Ñaareel", phonetic: "gnaaréél" },
      { french: "Troisième", wolof: "Ñetteel", phonetic: "gnettéél" },
      { french: "Compter à partir de", wolof: "Bàyyikoo", phonetic: "bàyyikoo" },
      { french: "Nombre / chiffre", wolof: "Lim", phonetic: "lim" },
      { french: "Peu / quantité faible", wolof: "Woyof", phonetic: "woyof" },
      { french: "Beaucoup / abondant", wolof: "Bare", phonetic: "bare" },
    ],
  },
  {
    id: "corps",
    title: "Le Corps",
    description: "Les parties du corps humain",
    emoji: "🧍",
    color: "#A8D8FF",
    bgColor: "#E0F0FF",
    words: [
      { french: "Tête", wolof: "Bopp", phonetic: "bopp" },
      { french: "Visage", wolof: "Kanam", phonetic: "kanam" },
      { french: "Œil / yeux", wolof: "Bët", phonetic: "beut" },
      { french: "Oreille", wolof: "Nopp", phonetic: "nopp" },
      { french: "Nez", wolof: "Bakkan", phonetic: "bakkan" },
      { french: "Bouche", wolof: "Gemmiñ", phonetic: "gemmign" },
      { french: "Dent", wolof: "Bëñ", phonetic: "beugn" },
      { french: "Langue", wolof: "Làmmiñ", phonetic: "làmmign" },
      { french: "Main / bras", wolof: "Loxo", phonetic: "lokho" },
      { french: "Doigt", wolof: "Baaraam", phonetic: "baaraam" },
      { french: "Pied / jambe", wolof: "Tànk", phonetic: "tànk" },
      { french: "Ventre", wolof: "Biir", phonetic: "biir" },
      { french: "Cœur", wolof: "Xol", phonetic: "khol" },
      { french: "Corps", wolof: "Yaram", phonetic: "yaram" },
      { french: "Peau", wolof: "Der", phonetic: "der" },
      { french: "Cheveux", wolof: "Kawar", phonetic: "kawar" },
      { french: "Cou", wolof: "Sabbu", phonetic: "sabbou" },
      { french: "Épaule", wolof: "Loxob ndey", phonetic: "lokhob ndey" },
      { french: "Dos", wolof: "Genn", phonetic: "genn" },
      { french: "Genou", wolof: "Këmb", phonetic: "keumb" },
    ],
  },
  {
    id: "nourriture",
    title: "Nourriture & Boissons",
    description: "Le vocabulaire de la nourriture et des boissons",
    emoji: "🍽️",
    color: "#FFD93D",
    bgColor: "#FFF8E0",
    words: [
      { french: "Riz", wolof: "Ceeb", phonetic: "tchééb" },
      { french: "Riz au poisson (plat national)", wolof: "Ceebu jën", phonetic: "tchéébou djeun" },
      { french: "Poisson", wolof: "Jën", phonetic: "djeun" },
      { french: "Viande", wolof: "Yàpp", phonetic: "yàpp" },
      { french: "Poulet", wolof: "Ganaar", phonetic: "ganaar" },
      { french: "Lait", wolof: "Meew", phonetic: "mééw" },
      { french: "Eau", wolof: "Ndox", phonetic: "ndokh" },
      { french: "Thé (préparé traditionnellement)", wolof: "Attaya", phonetic: "attaya" },
      { french: "Café", wolof: "Kafe", phonetic: "kafe" },
      { french: "Sucre", wolof: "Sukër", phonetic: "soukeur" },
      { french: "Sel", wolof: "Xorom", phonetic: "khorom" },
      { french: "Mangue", wolof: "Manko", phonetic: "manko" },
      { french: "Haricot", wolof: "Nebbe", phonetic: "nebbe" },
      { french: "Lait caillé", wolof: "Soow", phonetic: "soow" },
      { french: "Bouillie de mil", wolof: "Lakh", phonetic: "lakh" },
      { french: "Nourriture / manger", wolof: "Ñam", phonetic: "gnam" },
      { french: "Boire", wolof: "Naan", phonetic: "naan" },
      { french: "Cuisiner", wolof: "Togg", phonetic: "togg" },
      { french: "Riz aux haricots", wolof: "Ñebbe ak ceeb", phonetic: "gnebbe ak tchééb" },
      { french: "Huile", wolof: "Diw", phonetic: "diw" },
      { french: "Pain", wolof: "Mburu", phonetic: "mbourou" },
      { french: "Oignon", wolof: "Soble", phonetic: "soble" },
      { french: "Aubergine locale", wolof: "Jaxatu", phonetic: "djakhatou" },
      { french: "Piment", wolof: "Kaani", phonetic: "kaani" },
      { french: "Tomate", wolof: "Tamaate", phonetic: "tamaate" },
      { french: "Melon", wolof: "Xaal", phonetic: "khaal" },
      { french: "Noix de cola", wolof: "Guro", phonetic: "gouro" },
      { french: "Boisson à l'hibiscus", wolof: "Bissap", phonetic: "bissap" },
      { french: "Poisson séché", wolof: "Ndar", phonetic: "ndar" },
      { french: "Sardine", wolof: "Yaboy", phonetic: "yaboy" },
      { french: "S'il vous plaît (litt. si ça te plaît)", wolof: "Su néexee", phonetic: "sou néekhéé" },
      { french: "Avoir faim", wolof: "Xiif", phonetic: "khiif" },
      { french: "Avoir soif", wolof: "Mar", phonetic: "mar" },
      { french: "Être rassasié", wolof: "Suur", phonetic: "souur" },
      { french: "Beurre / matière grasse", wolof: "Diwtiir", phonetic: "diwtiir" },
      { french: "Petit-déjeuner à base de mil", wolof: "Njar-njar", phonetic: "ndjar-ndjar" },
      { french: "Dessert au mil et lait caillé", wolof: "Thiakry", phonetic: "thiakry" },
      { french: "Galette feuilletée", wolof: "Farata", phonetic: "farata" },
      { french: "Sandwich de haricots", wolof: "Ndambe", phonetic: "ndambe" },
      { french: "Soupe", wolof: "Soppa", phonetic: "soppa" },
    ],
  },
  {
    id: "couleurs",
    title: "Les Couleurs",
    description: "Toutes les couleurs en wolof",
    emoji: "🎨",
    color: "#FF9EBC",
    bgColor: "#FFE8F0",
    words: [
      { french: "Blanc", wolof: "Weex", phonetic: "wéékh" },
      { french: "Noir", wolof: "Ñuul", phonetic: "gnouul" },
      { french: "Rouge", wolof: "Xonq", phonetic: "khonk" },
      { french: "Vert", wolof: "Wert", phonetic: "wert" },
      { french: "Bleu", wolof: "Bulo", phonetic: "boulo" },
      { french: "Jaune / Couleur (en général)", wolof: "Melo", phonetic: "melo" },
      { french: "Gris", wolof: "Griz", phonetic: "griz" },
      { french: "Marron (couleur café)", wolof: "Kafe melo", phonetic: "kafe melo" },
      { french: "Couleur", wolof: "Nuur", phonetic: "nouur" },
      { french: "Clair (teint/couleur claire)", wolof: "Tàll", phonetic: "tàll" },
      { french: "Noir foncé", wolof: "Ñuul kukk", phonetic: "gnouul koukk" },
      { french: "Blanc éclatant", wolof: "Weex tàll", phonetic: "wéékh tàll" },
    ],
  },
  {
    id: "verbes",
    title: "Verbes Courants",
    description: "Les verbes essentiels du quotidien",
    emoji: "⚡",
    color: "#C3F0A2",
    bgColor: "#EEFBE0",
    words: [
      { french: "Aller", wolof: "Dem", phonetic: "dem" },
      { french: "Venir", wolof: "Ñëw", phonetic: "gneuw" },
      { french: "Faire", wolof: "Def", phonetic: "def" },
      { french: "Parler", wolof: "Wax", phonetic: "wakh" },
      { french: "Écouter / comprendre", wolof: "Dégg", phonetic: "dégg" },
      { french: "Voir", wolof: "Gis", phonetic: "gis" },
      { french: "Savoir / connaître", wolof: "Xam", phonetic: "kham" },
      { french: "Vouloir / aimer", wolof: "Bëgg", phonetic: "beugg" },
      { french: "Acheter", wolof: "Jënd", phonetic: "djeund" },
      { french: "Vendre", wolof: "Jaay", phonetic: "djaay" },
      { french: "Manger", wolof: "Lekk", phonetic: "lekk" },
      { french: "Boire", wolof: "Naan", phonetic: "naan" },
      { french: "S'asseoir", wolof: "Toog", phonetic: "toog" },
      { french: "Se lever / se tenir debout", wolof: "Taxaw", phonetic: "takhaw" },
      { french: "Marcher", wolof: "Dox", phonetic: "dokh" },
      { french: "Courir", wolof: "Daw", phonetic: "daw" },
      { french: "Dormir", wolof: "Nelaw", phonetic: "nelaw" },
      { french: "Se réveiller", wolof: "Yeewu", phonetic: "yééwou" },
      { french: "Écrire", wolof: "Bind", phonetic: "bind" },
      { french: "Lire / étudier", wolof: "Jàng", phonetic: "djàng" },
      { french: "Dire la vérité", wolof: "Wax dëgg", phonetic: "wakh deugg" },
      { french: "S'appeler / nommer", wolof: "Tudd", phonetic: "toudd" },
      { french: "Avoir", wolof: "Am", phonetic: "am" },
      { french: "Être / se trouver", wolof: "Nekk", phonetic: "nekk" },
      { french: "Préférer / être meilleur", wolof: "Gën", phonetic: "geun" },
      { french: "Envoyer", wolof: "Yónnee", phonetic: "yonnéé" },
      { french: "Provenir / partir de", wolof: "Jóge", phonetic: "djoge" },
      { french: "Retourner / revenir", wolof: "Dellu", phonetic: "dellou" },
      { french: "Travailler", wolof: "Liggéey", phonetic: "liggéey" },
      { french: "Cuisiner", wolof: "Togg", phonetic: "togg" },
      { french: "Se laver", wolof: "Sang", phonetic: "sang" },
      { french: "Laver (le linge)", wolof: "Fóot", phonetic: "foot" },
      { french: "Espérer", wolof: "Yaakaar", phonetic: "yaakaar" },
      { french: "Avoir peur", wolof: "Ragal", phonetic: "ragal" },
      { french: "Laisser / abandonner", wolof: "Bàyyi", phonetic: "bàyyi" },
      { french: "Donner (offrande)", wolof: "May", phonetic: "may" },
      { french: "Donner", wolof: "Jox", phonetic: "djokh" },
      { french: "Accepter", wolof: "Nangu", phonetic: "nangou" },
      { french: "Oublier", wolof: "Fàtte", phonetic: "fàtte" },
      { french: "Se souvenir", wolof: "Fàttaliku", phonetic: "fàttalikou" },
      { french: "Continuer", wolof: "Wéy", phonetic: "wéy" },
      { french: "S'entraîner", wolof: "Tàggat", phonetic: "tàggat" },
      { french: "Attendre", wolof: "Xaar", phonetic: "khaar" },
      { french: "Penser / réfléchir", wolof: "Xalaat", phonetic: "khalaat" },
      { french: "S'entendre bien", wolof: "Nangoo", phonetic: "nangoo" },
      { french: "Remercier", wolof: "Sant", phonetic: "sant" },
      { french: "Bouger", wolof: "Yëngu", phonetic: "yeungou" },
      { french: "Tromper", wolof: "Feem", phonetic: "féém" },
      { french: "Faire confiance", wolof: "Wóolu", phonetic: "woolou" },
      { french: "Être sûr / certain", wolof: "Wóor", phonetic: "woor" },
      { french: "Faciliter", wolof: "Yombal", phonetic: "yombal" },
    ],
  },
  {
    id: "questions",
    title: "Poser des Questions",
    description: "Les mots interrogatifs en wolof",
    emoji: "❓",
    color: "#FFD580",
    bgColor: "#FFF6D6",
    words: [
      { french: "Quoi", wolof: "Lan", phonetic: "lan" },
      { french: "Qui", wolof: "Kan", phonetic: "kan" },
      { french: "Où", wolof: "Fan", phonetic: "fan" },
      { french: "Quand", wolof: "Kañ", phonetic: "kagn" },
      { french: "Pourquoi", wolof: "Lu tax", phonetic: "lou takh" },
      { french: "Comment", wolof: "Naka", phonetic: "naka" },
      { french: "Combien", wolof: "Ñaata", phonetic: "gnaata" },
      { french: "C'est quand ?", wolof: "Kañ la", phonetic: "kagn la" },
      { french: "Lequel / laquelle", wolof: "Ban", phonetic: "ban" },
      { french: "Ce que / quoi (relatif)", wolof: "Lu", phonetic: "lou" },
    ],
  },
  {
    id: "maison-lecture",
    title: "Maison & Lecture",
    description: "Objets du quotidien, pièces de la maison, lire et écrire",
    emoji: "📖",
    color: "#8FD3D6",
    bgColor: "#E4F7F7",
    words: [
      { french: "Maison", wolof: "Kër", phonetic: "keur" },
      { french: "Chambre / pièce", wolof: "Néeg", phonetic: "néeg" },
      { french: "Porte de la maison", wolof: "Buntu kër", phonetic: "bountou keur" },
      { french: "Fenêtre", wolof: "Palanteer", phonetic: "palantéér" },
      { french: "Table", wolof: "Tabl", phonetic: "tabl" },
      { french: "Chaise", wolof: "Kaydaraa", phonetic: "kaydaraa" },
      { french: "Lit", wolof: "Lal", phonetic: "lal" },
      { french: "Récipient / marmite", wolof: "Ndab", phonetic: "ndab" },
      { french: "Cuillère", wolof: "Kuddu", phonetic: "kouddou" },
      { french: "Couteau", wolof: "Paaka", phonetic: "paaka" },
      { french: "Verre / tasse", wolof: "Kaas", phonetic: "kaas" },
      { french: "Savon", wolof: "Saabu", phonetic: "saabou" },
      { french: "Eau savonneuse", wolof: "Ndox saabu", phonetic: "ndokh saabou" },
      { french: "Rideau", wolof: "Riddo", phonetic: "riddo" },
      { french: "Lampe", wolof: "Ferñeetu", phonetic: "fergnéétou" },
      { french: "Balai", wolof: "Céy", phonetic: "tchéy" },
      { french: "Stylo", wolof: "Kalaam", phonetic: "kalaam" },
      { french: "Livre / cahier", wolof: "Téere", phonetic: "téere" },
      { french: "Sac", wolof: "Sàqar", phonetic: "sàkar" },
      { french: "Étudier / Lire", wolof: "Jàng", phonetic: "djàng" },
      { french: "Écrire", wolof: "Bind", phonetic: "bind" },
      { french: "Lettre", wolof: "Léetar", phonetic: "léetar" },
      { french: "Regarder", wolof: "Xool", phonetic: "khool", example: "Xoolal !", exampleTranslation: "Regarde !" },
      { french: "Goûter", wolof: "Mos", phonetic: "mos" },
      { french: "Toucher", wolof: "Lal", phonetic: "lal" },
      { french: "Ouvrir", wolof: "Ubbi", phonetic: "oubbi" },
      { french: "Fermer", wolof: "Tëj", phonetic: "teudj" },
      { french: "Entrer (dans)", wolof: "Dugg", phonetic: "dougg" },
      { french: "Sortir (de)", wolof: "Génn", phonetic: "génn" },
      { french: "Chercher", wolof: "Séet", phonetic: "séet" },
      { french: "À l'intérieur (de)", wolof: "Ci biir", phonetic: "tchi biir" },
      { french: "À l'extérieur (de)", wolof: "Ci biti", phonetic: "tchi biti" },
    ],
  },
  {
    id: "marche",
    title: "Au Marché",
    description: "Acheter, vendre, marchander et décrire les objets",
    emoji: "🛍️",
    color: "#FFB88C",
    bgColor: "#FFEFE3",
    words: [
      { french: "Marché", wolof: "Marse", phonetic: "marse" },
      { french: "Acheter", wolof: "Jënd", phonetic: "djeund" },
      { french: "Vendre", wolof: "Jaay", phonetic: "djaay" },
      { french: "Marchander", wolof: "Waxalé", phonetic: "wakhalé" },
      { french: "Offrir", wolof: "May", phonetic: "may" },
      { french: "Laisser", wolof: "Bàyyi", phonetic: "bàyyi" },
      { french: "Emmener / emporter", wolof: "Yoobu", phonetic: "yoobou" },
      { french: "Apporter", wolof: "Indi", phonetic: "indi" },
      { french: "Combien ça coûte ?", wolof: "Ñaata la ?", phonetic: "gnaata la ?" },
      { french: "S'il te plaît", wolof: "Su néexee", phonetic: "sou néekhéé" },
      { french: "Beau / bon", wolof: "Bon", phonetic: "bon" },
      { french: "Bon (variante)", wolof: "Bax", phonetic: "bakh" },
      { french: "Beau / joli", wolof: "Rafet", phonetic: "rafet" },
      { french: "Très mauvais", wolof: "Bon-bon", phonetic: "bon-bon" },
      { french: "Grand", wolof: "Réy", phonetic: "réy" },
      { french: "Petit / peu", wolof: "Tuuti", phonetic: "touuti" },
      { french: "Facile", wolof: "Yomb", phonetic: "yomb" },
      { french: "Difficile / lourd", wolof: "Diis", phonetic: "diis" },
      { french: "Rapide", wolof: "Gaaw", phonetic: "gaaw" },
      { french: "Lent", wolof: "Wexi", phonetic: "wekhi" },
      { french: "Froid", wolof: "Sedd", phonetic: "sedd" },
      { french: "Chaud", wolof: "Tàng", phonetic: "tàng" },
      { french: "Fin / mince", wolof: "Sew", phonetic: "sew" },
      { french: "Long", wolof: "Gudd", phonetic: "goudd" },
      { french: "Court", wolof: "Gàtt", phonetic: "gàtt" },
      { french: "Profond", wolof: "Xóot", phonetic: "khoot" },
      { french: "Plein", wolof: "Fees", phonetic: "féés" },
      { french: "Vide", wolof: "Neen", phonetic: "néén" },
      { french: "Important", wolof: "Am solo", phonetic: "am solo" },
      { french: "Propre", wolof: "Set", phonetic: "set" },
      { french: "Sale", wolof: "Tilim", phonetic: "tilim" },
      { french: "Douloureux / difficile", wolof: "Metti", phonetic: "metti" },
      { french: "Faible", wolof: "Néew", phonetic: "néew" },
      { french: "Fort / puissant", wolof: "Doole", phonetic: "doole" },
      { french: "Large", wolof: "Yaatu", phonetic: "yaatou" },
      { french: "Nouveau", wolof: "Bees", phonetic: "béés" },
    ],
  },
  {
    id: "temps",
    title: "Le Temps",
    description: "L'heure, les jours, les moments et la météo",
    emoji: "⏰",
    color: "#9EC6FF",
    bgColor: "#E8F1FF",
    words: [
      { french: "Jour", wolof: "Bés", phonetic: "bés" },
      { french: "Nuit", wolof: "Guddi", phonetic: "gouddi" },
      { french: "Matin / demain", wolof: "Suba", phonetic: "souba" },
      { french: "Après-midi / soir", wolof: "Ngoon", phonetic: "ngoon" },
      { french: "Aujourd'hui", wolof: "Tay", phonetic: "tay" },
      { french: "Hier", wolof: "Démb", phonetic: "démb" },
      { french: "Demain", wolof: "Éllëg", phonetic: "élleug" },
      { french: "Semaine", wolof: "Ayubés", phonetic: "ayoubés" },
      { french: "Mois / lune", wolof: "Weer", phonetic: "wéér" },
      { french: "Année", wolof: "At", phonetic: "at" },
      { french: "Lundi", wolof: "Altine", phonetic: "altine" },
      { french: "Mardi", wolof: "Talaata", phonetic: "talaata" },
      { french: "Mercredi", wolof: "Àllarba", phonetic: "àllarba" },
      { french: "Jeudi", wolof: "Alxamis", phonetic: "alkhamis" },
      { french: "Vendredi", wolof: "Àjjuma", phonetic: "àdjdjouma" },
      { french: "Samedi", wolof: "Gaawu", phonetic: "gaawou" },
      { french: "Dimanche", wolof: "Dibéer", phonetic: "dibéer" },
      { french: "Heure", wolof: "Waxtu", phonetic: "wakhtou" },
      { french: "Moment / instant", wolof: "Simili", phonetic: "simili" },
      { french: "Aube", wolof: "Njël", phonetic: "ndjeul" },
      { french: "Midi", wolof: "Tisbaar", phonetic: "tisbaar" },
      { french: "Crépuscule", wolof: "Timis", phonetic: "timis" },
      { french: "Aurore", wolof: "Fajar", phonetic: "fadjar" },
      { french: "Bientôt / dans peu de temps", wolof: "Ci kaw", phonetic: "tchi kaw" },
      { french: "Maintenant", wolof: "Léegi", phonetic: "léegi" },
      { french: "Il y a longtemps", wolof: "Bu yagg", phonetic: "bou yagg" },
      { french: "Se réveiller", wolof: "Yeewu", phonetic: "yééwou" },
      { french: "Dormir", wolof: "Nelaw", phonetic: "nelaw" },
      { french: "Passer la nuit", wolof: "Fanaan", phonetic: "fanaan" },
      { french: "Soleil", wolof: "Jant", phonetic: "djant" },
      { french: "Étoile", wolof: "Bittéel", phonetic: "bittéel" },
      { french: "Ciel", wolof: "Asamaan", phonetic: "asamaan" },
      { french: "Pluie", wolof: "Taw", phonetic: "taw" },
      { french: "Vent", wolof: "Ngelaw", phonetic: "ngelaw" },
      { french: "Chaleur", wolof: "Naaj", phonetic: "naadj" },
      { french: "Froid", wolof: "Sedd", phonetic: "sedd" },
      { french: "Nuage", wolof: "Xur", phonetic: "khour" },
    ],
  },
];

export type DictionaryEntry = WolofWord & { category: string };

export const dictionary: DictionaryEntry[] = [
  { french: "Bonjour (salutation la plus courante)", wolof: "Asalaamaalekum", phonetic: "asalaamaalekoum", category: "Salutations" },
  { french: "Réponse à « Asalaamaalekum »", wolof: "Maalekum salaam", phonetic: "maalekoum salaam", category: "Salutations" },
  { french: "Comment vas-tu ?", wolof: "Nanga def", phonetic: "nanga def", category: "Salutations" },
  { french: "Je vais bien (litt. je suis ici)", wolof: "Mangi fi", phonetic: "mangi fi", category: "Salutations" },
  { french: "Comment t'appelles-tu ?", wolof: "Naka nga tudd", phonetic: "naka nga toudd", category: "Salutations" },
  { french: "Je m'appelle...", wolof: "Maa ngi tudd...", phonetic: "maa ngi toudd...", category: "Salutations" },
  { french: "À la prochaine fois", wolof: "Ba beneen yoon", phonetic: "ba benéén yoon", category: "Salutations" },
  { french: "À demain", wolof: "Ba suba", phonetic: "ba souba", category: "Salutations" },
  { french: "Merci", wolof: "Jërejëf", phonetic: "djeuredjeuf", category: "Salutations" },
  { french: "Il n'y a pas de quoi / de rien", wolof: "Amul solo", phonetic: "amoul solo", category: "Salutations" },
  { french: "Excuse-moi / pardonne-moi", wolof: "Baal ma", phonetic: "baal ma", category: "Salutations" },
  { french: "Oui", wolof: "Waaw", phonetic: "waaw", category: "Salutations" },
  { french: "Non", wolof: "Déedéet", phonetic: "déedéet", category: "Salutations" },
  { french: "Remercier", wolof: "Sant", phonetic: "sant", category: "Salutations" },
  { french: "Bienvenue (litt. installe-toi en paix)", wolof: "Dalal ak jamm", phonetic: "dalal ak djamm", category: "Salutations" },
  { french: "Tout va bien (litt. paix seulement)", wolof: "Jamm rekk", phonetic: "djamm rekk", category: "Salutations" },
  { french: "Comment va la famille ?", wolof: "Naka waa kër ga", phonetic: "naka waa keur ga", category: "Salutations" },
  { french: "Ils vont bien / ils sont là", wolof: "Ñu ngi fi", phonetic: "gnou ngi fi", category: "Salutations" },
  { french: "D'où viens-tu ?", wolof: "Foo jogé", phonetic: "foo djogé", category: "Salutations" },
  { french: "Moi, je... (pour se présenter)", wolof: "Man...", phonetic: "man...", category: "Salutations" },
  { french: "Comment vas-tu ?", wolof: "Nanga def ?", phonetic: "nanga def ?", category: "Expressions courantes" },
  { french: "Je vais bien, tout simplement", wolof: "Mangi fi rekk", phonetic: "mangi fi rekk", category: "Expressions courantes" },
  { french: "Comment va la famille ?", wolof: "Ana waa kër ga ?", phonetic: "ana waa keur ga ?", category: "Expressions courantes" },
  { french: "Merci mais...", wolof: "Jërejëf waaye", phonetic: "djeuredjeuf waaye", category: "Expressions courantes" },
  { french: "Si Dieu le veut", wolof: "Su ëllëgee", phonetic: "sou eulleugéé", category: "Expressions courantes" },
  { french: "Excuse-moi car...", wolof: "Baal ma ndax...", phonetic: "baal ma ndakh...", category: "Expressions courantes" },
  { french: "Où vas-tu ?", wolof: "Foo jëm ?", phonetic: "foo djeum ?", category: "Expressions courantes" },
  { french: "Je m'en vais", wolof: "Damay dem", phonetic: "damay dem", category: "Expressions courantes" },
  { french: "Comment vont les gens ?", wolof: "Naka gaa ngi ?", phonetic: "naka gaa ngi ?", category: "Expressions courantes" },
  { french: "Est-ce que tu... ?", wolof: "Xanaa dangaa..?", phonetic: "khanaa dangaa..?", category: "Expressions courantes" },
  { french: "Si jamais... / au cas où...", wolof: "Su fekkee...", phonetic: "sou fekkéé...", category: "Expressions courantes" },
  { french: "J'ai envie de manger", wolof: "Dama bëgga lekk", phonetic: "dama beugga lekk", category: "Expressions courantes" },
  { french: "Je suis fatigué(e)", wolof: "Dama sonn", phonetic: "dama sonn", category: "Expressions courantes" },
  { french: "J'ai faim", wolof: "Dama xiif", phonetic: "dama khiif", category: "Expressions courantes" },
  { french: "J'ai soif", wolof: "Dama mar", phonetic: "dama mar", category: "Expressions courantes" },
  { french: "Où habites-tu ?", wolof: "Fan nga dëkk ?", phonetic: "fan nga deukk ?", category: "Expressions courantes" },
  { french: "Moi, j'habite à...", wolof: "Man dama dëkk ci...", phonetic: "man dama deukk tchi...", category: "Expressions courantes" },
  { french: "Combien ça coûte ?", wolof: "Ñaata la ?", phonetic: "gnaata la ?", category: "Expressions courantes" },
  { french: "Je voudrais acheter...", wolof: "Dama bëgga jënd...", phonetic: "dama beugga djeund...", category: "Expressions courantes" },
  { french: "Si tu veux bien / s'il te plaît", wolof: "Su ko neexee", phonetic: "sou ko néékhéé", category: "Expressions courantes" },
  { french: "Je te fais confiance", wolof: "Wóolu naa la", phonetic: "woolou naa la", category: "Expressions courantes" },
  { french: "Tout de suite", wolof: "Léegi léegi", phonetic: "léegi léegi", category: "Expressions courantes" },
  { french: "À plus tard", wolof: "Ba beneen", phonetic: "ba benéén", category: "Expressions courantes" },
  { french: "Que Dieu t'accorde la paix", wolof: "Yàlla na la may jamm", phonetic: "yàlla na la may djamm", category: "Expressions courantes" },
  { french: "Ne t'inquiète pas (litt. il n'a rien fait)", wolof: "Deful dara", phonetic: "defoul dara", category: "Expressions courantes" },
  { french: "Tu sais ? / Tu comprends ?", wolof: "Xam nga ?", phonetic: "kham nga ?", category: "Expressions courantes" },
  { french: "Oui, je sais", wolof: "Waaw, xam naa", phonetic: "waaw, kham naa", category: "Expressions courantes" },
  { french: "Non, je ne sais pas", wolof: "Déedéet, xamuma", phonetic: "déedéet, khamouma", category: "Expressions courantes" },
  { french: "Moi / je", wolof: "Man", phonetic: "man", category: "Pronoms" },
  { french: "Toi / tu", wolof: "Yow", phonetic: "yow", category: "Pronoms" },
  { french: "Lui / elle", wolof: "Moom", phonetic: "moom", category: "Pronoms" },
  { french: "Nous", wolof: "Ñun", phonetic: "gnoun", category: "Pronoms" },
  { french: "Vous", wolof: "Yéen", phonetic: "yéen", category: "Pronoms" },
  { french: "Eux / elles", wolof: "Ñoom", phonetic: "gnoom", category: "Pronoms" },
  { french: "Mon / ma", wolof: "Sama", phonetic: "sama", category: "Pronoms" },
  { french: "Ton / ta", wolof: "Sa", phonetic: "sa", category: "Pronoms" },
  { french: "Notre", wolof: "Sunu", phonetic: "sounou", category: "Pronoms" },
  { french: "Votre / leur", wolof: "Seen", phonetic: "séén", category: "Pronoms" },
  { french: "Maison / famille", wolof: "Kër", phonetic: "keur", category: "Famille" },
  { french: "Père", wolof: "Baay", phonetic: "baay", category: "Famille" },
  { french: "Mère", wolof: "Yaay", phonetic: "yaay", category: "Famille" },
  { french: "Enfant (fils/fille)", wolof: "Doom", phonetic: "doom", category: "Famille" },
  { french: "Épouse", wolof: "Jabar", phonetic: "djabar", category: "Famille" },
  { french: "Époux", wolof: "Jëkkër", phonetic: "djeukkeur", category: "Famille" },
  { french: "Aîné(e)", wolof: "Mag", phonetic: "mag", category: "Famille" },
  { french: "Cadet(te)", wolof: "Rakk", phonetic: "rakk", category: "Famille" },
  { french: "Grand-mère", wolof: "Mamdaam", phonetic: "mamdaam", category: "Famille" },
  { french: "Grand-père (variante régionale)", wolof: "Mamdiop", phonetic: "mamdiop", category: "Famille" },
  { french: "Oncle maternel", wolof: "Nijaay", phonetic: "nidjaay", category: "Famille" },
  { french: "Tante paternelle", wolof: "Bàjjan", phonetic: "bàdjdjan", category: "Famille" },
  { french: "Ami(e)", wolof: "Xarit", phonetic: "kharit", category: "Famille" },
  { french: "Chef de famille", wolof: "Jëkkëru njaboot", phonetic: "djeukkeurou ndjaboot", category: "Famille" },
  { french: "Famille (au sens large)", wolof: "Njaboot", phonetic: "ndjaboot", category: "Famille" },
  { french: "Cousin(e)", wolof: "Sët", phonetic: "seut", category: "Famille" },
  { french: "Homme / garçon", wolof: "Góor", phonetic: "goor", category: "Famille" },
  { french: "Femme / fille", wolof: "Jigéen", phonetic: "djigéen", category: "Famille" },
  { french: "Parents", wolof: "Waa jur", phonetic: "waa djour", category: "Famille" },
  { french: "Accoucher / donner naissance", wolof: "Jur", phonetic: "djour", category: "Famille" },
  { french: "Se marier", wolof: "Sey", phonetic: "sey", category: "Famille" },
  { french: "Coépouse", wolof: "Nag", phonetic: "nag", category: "Famille" },
  { french: "Marraine", wolof: "Ndeye ji", phonetic: "ndeye dji", category: "Famille" },
  { french: "Parrain", wolof: "Baay ji", phonetic: "baay dji", category: "Famille" },
  { french: "Nouveau-né", wolof: "Njël", phonetic: "ndjeul", category: "Famille" },
  { french: "0 / Zéro", wolof: "Tus", phonetic: "tous", category: "Chiffres" },
  { french: "1", wolof: "Benn", phonetic: "benn", category: "Chiffres" },
  { french: "2", wolof: "Ñaar", phonetic: "gnaar", category: "Chiffres" },
  { french: "3", wolof: "Ñett", phonetic: "gnett", category: "Chiffres" },
  { french: "4", wolof: "Ñeent", phonetic: "gnéént", category: "Chiffres" },
  { french: "5", wolof: "Juróom", phonetic: "djouroom", category: "Chiffres" },
  { french: "6", wolof: "Juróom-benn", phonetic: "djouroom-benn", category: "Chiffres" },
  { french: "7", wolof: "Juróom-ñaar", phonetic: "djouroom-gnaar", category: "Chiffres" },
  { french: "8", wolof: "Juróom-ñett", phonetic: "djouroom-gnett", category: "Chiffres" },
  { french: "9", wolof: "Juróom-ñeent", phonetic: "djouroom-gnéént", category: "Chiffres" },
  { french: "10", wolof: "Fukk", phonetic: "foukk", category: "Chiffres" },
  { french: "11", wolof: "Fukk ak benn", phonetic: "foukk ak benn", category: "Chiffres" },
  { french: "12", wolof: "Fukk ak ñaar", phonetic: "foukk ak gnaar", category: "Chiffres" },
  { french: "13", wolof: "Fukk ak ñett", phonetic: "foukk ak gnett", category: "Chiffres" },
  { french: "14", wolof: "Fukk ak ñeent", phonetic: "foukk ak gnéént", category: "Chiffres" },
  { french: "15", wolof: "Fukk ak juróom", phonetic: "foukk ak djouroom", category: "Chiffres" },
  { french: "16", wolof: "Fukk ak juróom-benn", phonetic: "foukk ak djouroom-benn", category: "Chiffres" },
  { french: "17", wolof: "Fukk ak juróom-ñaar", phonetic: "foukk ak djouroom-gnaar", category: "Chiffres" },
  { french: "18", wolof: "Fukk ak juróom-ñett", phonetic: "foukk ak djouroom-gnett", category: "Chiffres" },
  { french: "19", wolof: "Fukk ak juróom-ñeent", phonetic: "foukk ak djouroom-gnéént", category: "Chiffres" },
  { french: "20", wolof: "Ñaar-fukk", phonetic: "gnaar-foukk", category: "Chiffres" },
  { french: "21", wolof: "Ñaar-fukk ak benn", phonetic: "gnaar-foukk ak benn", category: "Chiffres" },
  { french: "22", wolof: "Ñaar-fukk ak ñaar", phonetic: "gnaar-foukk ak gnaar", category: "Chiffres" },
  { french: "24", wolof: "Ñaar-fukk ak ñeent", phonetic: "gnaar-foukk ak gnéént", category: "Chiffres" },
  { french: "25", wolof: "Ñaar-fukk ak juróom", phonetic: "gnaar-foukk ak djouroom", category: "Chiffres" },
  { french: "30", wolof: "Ñett-fukk", phonetic: "gnett-foukk", category: "Chiffres" },
  { french: "32", wolof: "Ñett-fukk ak ñaar", phonetic: "gnett-foukk ak gnaar", category: "Chiffres" },
  { french: "33", wolof: "Ñett-fukk ak ñett", phonetic: "gnett-foukk ak gnett", category: "Chiffres" },
  { french: "35", wolof: "Ñett-fukk ak juróom", phonetic: "gnett-foukk ak djouroom", category: "Chiffres" },
  { french: "40", wolof: "Ñeent-fukk", phonetic: "gnéént-foukk", category: "Chiffres" },
  { french: "44", wolof: "Ñeent-fukk ak ñeent", phonetic: "gnéént-foukk ak gnéént", category: "Chiffres" },
  { french: "45", wolof: "Ñeent-fukk ak juróom", phonetic: "gnéént-foukk ak djouroom", category: "Chiffres" },
  { french: "50", wolof: "Juróom-fukk", phonetic: "djouroom-foukk", category: "Chiffres" },
  { french: "55", wolof: "Juróom-fukk ak juróom", phonetic: "djouroom-foukk ak djouroom", category: "Chiffres" },
  { french: "60", wolof: "Juróom-benn fukk", phonetic: "djouroom-benn foukk", category: "Chiffres" },
  { french: "70", wolof: "Juróom-ñaar fukk", phonetic: "djouroom-gnaar foukk", category: "Chiffres" },
  { french: "80", wolof: "Juróom-ñett fukk", phonetic: "djouroom-gnett foukk", category: "Chiffres" },
  { french: "90", wolof: "Juróom-ñeent fukk", phonetic: "djouroom-gnéént foukk", category: "Chiffres" },
  { french: "99", wolof: "Juróom-ñeent fukk ak juróom-ñeent", phonetic: "djouroom-gnéént foukk ak djouroom-gnéént", category: "Chiffres" },
  { french: "100", wolof: "Téeméer", phonetic: "téeméer", category: "Chiffres" },
  { french: "200", wolof: "Ñaar téeméer", phonetic: "gnaar téeméer", category: "Chiffres" },
  { french: "300", wolof: "Ñett téeméer", phonetic: "gnett téeméer", category: "Chiffres" },
  { french: "500", wolof: "Juróom téeméer", phonetic: "djouroom téeméer", category: "Chiffres" },
  { french: "1000", wolof: "Junni", phonetic: "djounni", category: "Chiffres" },
  { french: "2000", wolof: "Ñaar junni", phonetic: "gnaar djounni", category: "Chiffres" },
  { french: "Premier", wolof: "Njëkk", phonetic: "ndjeukk", category: "Chiffres" },
  { french: "Deuxième", wolof: "Ñaareel", phonetic: "gnaaréél", category: "Chiffres" },
  { french: "Troisième", wolof: "Ñetteel", phonetic: "gnettéél", category: "Chiffres" },
  { french: "Compter à partir de", wolof: "Bàyyikoo", phonetic: "bàyyikoo", category: "Chiffres" },
  { french: "Nombre / chiffre", wolof: "Lim", phonetic: "lim", category: "Chiffres" },
  { french: "Peu / quantité faible", wolof: "Woyof", phonetic: "woyof", category: "Chiffres" },
  { french: "Beaucoup / abondant", wolof: "Bare", phonetic: "bare", category: "Chiffres" },
  { french: "Tête", wolof: "Bopp", phonetic: "bopp", category: "Corps" },
  { french: "Visage", wolof: "Kanam", phonetic: "kanam", category: "Corps" },
  { french: "Œil / yeux", wolof: "Bët", phonetic: "beut", category: "Corps" },
  { french: "Oreille", wolof: "Nopp", phonetic: "nopp", category: "Corps" },
  { french: "Nez", wolof: "Bakkan", phonetic: "bakkan", category: "Corps" },
  { french: "Bouche", wolof: "Gemmiñ", phonetic: "gemmign", category: "Corps" },
  { french: "Dent", wolof: "Bëñ", phonetic: "beugn", category: "Corps" },
  { french: "Langue", wolof: "Làmmiñ", phonetic: "làmmign", category: "Corps" },
  { french: "Main / bras", wolof: "Loxo", phonetic: "lokho", category: "Corps" },
  { french: "Doigt", wolof: "Baaraam", phonetic: "baaraam", category: "Corps" },
  { french: "Pied / jambe", wolof: "Tànk", phonetic: "tànk", category: "Corps" },
  { french: "Ventre", wolof: "Biir", phonetic: "biir", category: "Corps" },
  { french: "Cœur", wolof: "Xol", phonetic: "khol", category: "Corps" },
  { french: "Corps", wolof: "Yaram", phonetic: "yaram", category: "Corps" },
  { french: "Peau", wolof: "Der", phonetic: "der", category: "Corps" },
  { french: "Cheveux", wolof: "Kawar", phonetic: "kawar", category: "Corps" },
  { french: "Cou", wolof: "Sabbu", phonetic: "sabbou", category: "Corps" },
  { french: "Épaule", wolof: "Loxob ndey", phonetic: "lokhob ndey", category: "Corps" },
  { french: "Dos", wolof: "Genn", phonetic: "genn", category: "Corps" },
  { french: "Genou", wolof: "Këmb", phonetic: "keumb", category: "Corps" },
  { french: "Riz", wolof: "Ceeb", phonetic: "tchééb", category: "Nourriture" },
  { french: "Riz au poisson (plat national)", wolof: "Ceebu jën", phonetic: "tchéébou djeun", category: "Nourriture" },
  { french: "Poisson", wolof: "Jën", phonetic: "djeun", category: "Nourriture" },
  { french: "Viande", wolof: "Yàpp", phonetic: "yàpp", category: "Nourriture" },
  { french: "Poulet", wolof: "Ganaar", phonetic: "ganaar", category: "Nourriture" },
  { french: "Lait", wolof: "Meew", phonetic: "mééw", category: "Nourriture" },
  { french: "Eau", wolof: "Ndox", phonetic: "ndokh", category: "Nourriture" },
  { french: "Thé (préparé traditionnellement)", wolof: "Attaya", phonetic: "attaya", category: "Nourriture" },
  { french: "Café", wolof: "Kafe", phonetic: "kafe", category: "Nourriture" },
  { french: "Sucre", wolof: "Sukër", phonetic: "soukeur", category: "Nourriture" },
  { french: "Sel", wolof: "Xorom", phonetic: "khorom", category: "Nourriture" },
  { french: "Mangue", wolof: "Manko", phonetic: "manko", category: "Nourriture" },
  { french: "Haricot", wolof: "Nebbe", phonetic: "nebbe", category: "Nourriture" },
  { french: "Lait caillé", wolof: "Soow", phonetic: "soow", category: "Nourriture" },
  { french: "Bouillie de mil", wolof: "Lakh", phonetic: "lakh", category: "Nourriture" },
  { french: "Nourriture / manger", wolof: "Ñam", phonetic: "gnam", category: "Nourriture" },
  { french: "Boire", wolof: "Naan", phonetic: "naan", category: "Nourriture" },
  { french: "Cuisiner", wolof: "Togg", phonetic: "togg", category: "Nourriture" },
  { french: "Riz aux haricots", wolof: "Ñebbe ak ceeb", phonetic: "gnebbe ak tchééb", category: "Nourriture" },
  { french: "Huile", wolof: "Diw", phonetic: "diw", category: "Nourriture" },
  { french: "Pain", wolof: "Mburu", phonetic: "mbourou", category: "Nourriture" },
  { french: "Oignon", wolof: "Soble", phonetic: "soble", category: "Nourriture" },
  { french: "Aubergine locale", wolof: "Jaxatu", phonetic: "djakhatou", category: "Nourriture" },
  { french: "Piment", wolof: "Kaani", phonetic: "kaani", category: "Nourriture" },
  { french: "Tomate", wolof: "Tamaate", phonetic: "tamaate", category: "Nourriture" },
  { french: "Melon", wolof: "Xaal", phonetic: "khaal", category: "Nourriture" },
  { french: "Noix de cola", wolof: "Guro", phonetic: "gouro", category: "Nourriture" },
  { french: "Boisson à l'hibiscus", wolof: "Bissap", phonetic: "bissap", category: "Nourriture" },
  { french: "Poisson séché", wolof: "Ndar", phonetic: "ndar", category: "Nourriture" },
  { french: "Sardine", wolof: "Yaboy", phonetic: "yaboy", category: "Nourriture" },
  { french: "S'il vous plaît (litt. si ça te plaît)", wolof: "Su néexee", phonetic: "sou néekhéé", category: "Nourriture" },
  { french: "Avoir faim", wolof: "Xiif", phonetic: "khiif", category: "Nourriture" },
  { french: "Avoir soif", wolof: "Mar", phonetic: "mar", category: "Nourriture" },
  { french: "Être rassasié", wolof: "Suur", phonetic: "souur", category: "Nourriture" },
  { french: "Beurre / matière grasse", wolof: "Diwtiir", phonetic: "diwtiir", category: "Nourriture" },
  { french: "Petit-déjeuner à base de mil", wolof: "Njar-njar", phonetic: "ndjar-ndjar", category: "Nourriture" },
  { french: "Dessert au mil et lait caillé", wolof: "Thiakry", phonetic: "thiakry", category: "Nourriture" },
  { french: "Galette feuilletée", wolof: "Farata", phonetic: "farata", category: "Nourriture" },
  { french: "Sandwich de haricots", wolof: "Ndambe", phonetic: "ndambe", category: "Nourriture" },
  { french: "Soupe", wolof: "Soppa", phonetic: "soppa", category: "Nourriture" },
  { french: "Blanc", wolof: "Weex", phonetic: "wéékh", category: "Couleurs" },
  { french: "Noir", wolof: "Ñuul", phonetic: "gnouul", category: "Couleurs" },
  { french: "Rouge", wolof: "Xonq", phonetic: "khonk", category: "Couleurs" },
  { french: "Vert", wolof: "Wert", phonetic: "wert", category: "Couleurs" },
  { french: "Bleu", wolof: "Bulo", phonetic: "boulo", category: "Couleurs" },
  { french: "Jaune / Couleur (en général)", wolof: "Melo", phonetic: "melo", category: "Couleurs" },
  { french: "Gris", wolof: "Griz", phonetic: "griz", category: "Couleurs" },
  { french: "Marron (couleur café)", wolof: "Kafe melo", phonetic: "kafe melo", category: "Couleurs" },
  { french: "Couleur", wolof: "Nuur", phonetic: "nouur", category: "Couleurs" },
  { french: "Clair (teint/couleur claire)", wolof: "Tàll", phonetic: "tàll", category: "Couleurs" },
  { french: "Noir foncé", wolof: "Ñuul kukk", phonetic: "gnouul koukk", category: "Couleurs" },
  { french: "Blanc éclatant", wolof: "Weex tàll", phonetic: "wéékh tàll", category: "Couleurs" },
  { french: "Aller", wolof: "Dem", phonetic: "dem", category: "Verbes" },
  { french: "Venir", wolof: "Ñëw", phonetic: "gneuw", category: "Verbes" },
  { french: "Faire", wolof: "Def", phonetic: "def", category: "Verbes" },
  { french: "Parler", wolof: "Wax", phonetic: "wakh", category: "Verbes" },
  { french: "Écouter / comprendre", wolof: "Dégg", phonetic: "dégg", category: "Verbes" },
  { french: "Voir", wolof: "Gis", phonetic: "gis", category: "Verbes" },
  { french: "Savoir / connaître", wolof: "Xam", phonetic: "kham", category: "Verbes" },
  { french: "Vouloir / aimer", wolof: "Bëgg", phonetic: "beugg", category: "Verbes" },
  { french: "Acheter", wolof: "Jënd", phonetic: "djeund", category: "Verbes" },
  { french: "Vendre", wolof: "Jaay", phonetic: "djaay", category: "Verbes" },
  { french: "Manger", wolof: "Lekk", phonetic: "lekk", category: "Verbes" },
  { french: "S'asseoir", wolof: "Toog", phonetic: "toog", category: "Verbes" },
  { french: "Se lever / se tenir debout", wolof: "Taxaw", phonetic: "takhaw", category: "Verbes" },
  { french: "Marcher", wolof: "Dox", phonetic: "dokh", category: "Verbes" },
  { french: "Courir", wolof: "Daw", phonetic: "daw", category: "Verbes" },
  { french: "Dormir", wolof: "Nelaw", phonetic: "nelaw", category: "Verbes" },
  { french: "Se réveiller", wolof: "Yeewu", phonetic: "yééwou", category: "Verbes" },
  { french: "Écrire", wolof: "Bind", phonetic: "bind", category: "Verbes" },
  { french: "Lire / étudier", wolof: "Jàng", phonetic: "djàng", category: "Verbes" },
  { french: "Dire la vérité", wolof: "Wax dëgg", phonetic: "wakh deugg", category: "Verbes" },
  { french: "S'appeler / nommer", wolof: "Tudd", phonetic: "toudd", category: "Verbes" },
  { french: "Avoir", wolof: "Am", phonetic: "am", category: "Verbes" },
  { french: "Être / se trouver", wolof: "Nekk", phonetic: "nekk", category: "Verbes" },
  { french: "Préférer / être meilleur", wolof: "Gën", phonetic: "geun", category: "Verbes" },
  { french: "Envoyer", wolof: "Yónnee", phonetic: "yonnéé", category: "Verbes" },
  { french: "Provenir / partir de", wolof: "Jóge", phonetic: "djoge", category: "Verbes" },
  { french: "Retourner / revenir", wolof: "Dellu", phonetic: "dellou", category: "Verbes" },
  { french: "Travailler", wolof: "Liggéey", phonetic: "liggéey", category: "Verbes" },
  { french: "Se laver", wolof: "Sang", phonetic: "sang", category: "Verbes" },
  { french: "Laver (le linge)", wolof: "Fóot", phonetic: "foot", category: "Verbes" },
  { french: "Espérer", wolof: "Yaakaar", phonetic: "yaakaar", category: "Verbes" },
  { french: "Avoir peur", wolof: "Ragal", phonetic: "ragal", category: "Verbes" },
  { french: "Laisser / abandonner", wolof: "Bàyyi", phonetic: "bàyyi", category: "Verbes" },
  { french: "Donner (offrande)", wolof: "May", phonetic: "may", category: "Verbes" },
  { french: "Donner", wolof: "Jox", phonetic: "djokh", category: "Verbes" },
  { french: "Accepter", wolof: "Nangu", phonetic: "nangou", category: "Verbes" },
  { french: "Oublier", wolof: "Fàtte", phonetic: "fàtte", category: "Verbes" },
  { french: "Se souvenir", wolof: "Fàttaliku", phonetic: "fàttalikou", category: "Verbes" },
  { french: "Continuer", wolof: "Wéy", phonetic: "wéy", category: "Verbes" },
  { french: "S'entraîner", wolof: "Tàggat", phonetic: "tàggat", category: "Verbes" },
  { french: "Attendre", wolof: "Xaar", phonetic: "khaar", category: "Verbes" },
  { french: "Penser / réfléchir", wolof: "Xalaat", phonetic: "khalaat", category: "Verbes" },
  { french: "S'entendre bien", wolof: "Nangoo", phonetic: "nangoo", category: "Verbes" },
  { french: "Bouger", wolof: "Yëngu", phonetic: "yeungou", category: "Verbes" },
  { french: "Tromper", wolof: "Feem", phonetic: "féém", category: "Verbes" },
  { french: "Faire confiance", wolof: "Wóolu", phonetic: "woolou", category: "Verbes" },
  { french: "Être sûr / certain", wolof: "Wóor", phonetic: "woor", category: "Verbes" },
  { french: "Faciliter", wolof: "Yombal", phonetic: "yombal", category: "Verbes" },
  { french: "Quoi", wolof: "Lan", phonetic: "lan", category: "Questions" },
  { french: "Qui", wolof: "Kan", phonetic: "kan", category: "Questions" },
  { french: "Où", wolof: "Fan", phonetic: "fan", category: "Questions" },
  { french: "Quand", wolof: "Kañ", phonetic: "kagn", category: "Questions" },
  { french: "Pourquoi", wolof: "Lu tax", phonetic: "lou takh", category: "Questions" },
  { french: "Comment", wolof: "Naka", phonetic: "naka", category: "Questions" },
  { french: "Combien", wolof: "Ñaata", phonetic: "gnaata", category: "Questions" },
  { french: "C'est quand ?", wolof: "Kañ la", phonetic: "kagn la", category: "Questions" },
  { french: "Lequel / laquelle", wolof: "Ban", phonetic: "ban", category: "Questions" },
  { french: "Ce que / quoi (relatif)", wolof: "Lu", phonetic: "lou", category: "Questions" },
  { french: "Maison", wolof: "Kër", phonetic: "keur", category: "Maison" },
  { french: "Chambre / pièce", wolof: "Néeg", phonetic: "néeg", category: "Maison" },
  { french: "Porte de la maison", wolof: "Buntu kër", phonetic: "bountou keur", category: "Maison" },
  { french: "Fenêtre", wolof: "Palanteer", phonetic: "palantéér", category: "Maison" },
  { french: "Table", wolof: "Tabl", phonetic: "tabl", category: "Maison" },
  { french: "Chaise", wolof: "Kaydaraa", phonetic: "kaydaraa", category: "Maison" },
  { french: "Lit", wolof: "Lal", phonetic: "lal", category: "Maison" },
  { french: "Récipient / marmite", wolof: "Ndab", phonetic: "ndab", category: "Maison" },
  { french: "Cuillère", wolof: "Kuddu", phonetic: "kouddou", category: "Maison" },
  { french: "Couteau", wolof: "Paaka", phonetic: "paaka", category: "Maison" },
  { french: "Verre / tasse", wolof: "Kaas", phonetic: "kaas", category: "Maison" },
  { french: "Savon", wolof: "Saabu", phonetic: "saabou", category: "Maison" },
  { french: "Eau savonneuse", wolof: "Ndox saabu", phonetic: "ndokh saabou", category: "Maison" },
  { french: "Rideau", wolof: "Riddo", phonetic: "riddo", category: "Maison" },
  { french: "Lampe", wolof: "Ferñeetu", phonetic: "fergnéétou", category: "Maison" },
  { french: "Balai", wolof: "Céy", phonetic: "tchéy", category: "Maison" },
  { french: "Stylo", wolof: "Kalaam", phonetic: "kalaam", category: "Maison" },
  { french: "Livre / cahier", wolof: "Téere", phonetic: "téere", category: "Maison" },
  { french: "Sac", wolof: "Sàqar", phonetic: "sàkar", category: "Maison" },
  { french: "Étudier / Lire", wolof: "Jàng", phonetic: "djàng", category: "Maison" },
  { french: "Lettre", wolof: "Léetar", phonetic: "léetar", category: "Maison" },
  { french: "Regarder", wolof: "Xool", phonetic: "khool", category: "Maison" },
  { french: "Goûter", wolof: "Mos", phonetic: "mos", category: "Maison" },
  { french: "Toucher", wolof: "Lal", phonetic: "lal", category: "Maison" },
  { french: "Ouvrir", wolof: "Ubbi", phonetic: "oubbi", category: "Maison" },
  { french: "Fermer", wolof: "Tëj", phonetic: "teudj", category: "Maison" },
  { french: "Entrer (dans)", wolof: "Dugg", phonetic: "dougg", category: "Maison" },
  { french: "Sortir (de)", wolof: "Génn", phonetic: "génn", category: "Maison" },
  { french: "Chercher", wolof: "Séet", phonetic: "séet", category: "Maison" },
  { french: "À l'intérieur (de)", wolof: "Ci biir", phonetic: "tchi biir", category: "Maison" },
  { french: "À l'extérieur (de)", wolof: "Ci biti", phonetic: "tchi biti", category: "Maison" },
  { french: "Marché", wolof: "Marse", phonetic: "marse", category: "Marché & Adjectifs" },
  { french: "Marchander", wolof: "Waxalé", phonetic: "wakhalé", category: "Marché & Adjectifs" },
  { french: "Offrir", wolof: "May", phonetic: "may", category: "Marché & Adjectifs" },
  { french: "Laisser", wolof: "Bàyyi", phonetic: "bàyyi", category: "Marché & Adjectifs" },
  { french: "Emmener / emporter", wolof: "Yoobu", phonetic: "yoobou", category: "Marché & Adjectifs" },
  { french: "Apporter", wolof: "Indi", phonetic: "indi", category: "Marché & Adjectifs" },
  { french: "S'il te plaît", wolof: "Su néexee", phonetic: "sou néekhéé", category: "Marché & Adjectifs" },
  { french: "Beau / bon", wolof: "Bon", phonetic: "bon", category: "Marché & Adjectifs" },
  { french: "Bon (variante)", wolof: "Bax", phonetic: "bakh", category: "Marché & Adjectifs" },
  { french: "Beau / joli", wolof: "Rafet", phonetic: "rafet", category: "Marché & Adjectifs" },
  { french: "Très mauvais", wolof: "Bon-bon", phonetic: "bon-bon", category: "Marché & Adjectifs" },
  { french: "Grand", wolof: "Réy", phonetic: "réy", category: "Marché & Adjectifs" },
  { french: "Petit / peu", wolof: "Tuuti", phonetic: "touuti", category: "Marché & Adjectifs" },
  { french: "Facile", wolof: "Yomb", phonetic: "yomb", category: "Marché & Adjectifs" },
  { french: "Difficile / lourd", wolof: "Diis", phonetic: "diis", category: "Marché & Adjectifs" },
  { french: "Rapide", wolof: "Gaaw", phonetic: "gaaw", category: "Marché & Adjectifs" },
  { french: "Lent", wolof: "Wexi", phonetic: "wekhi", category: "Marché & Adjectifs" },
  { french: "Froid", wolof: "Sedd", phonetic: "sedd", category: "Marché & Adjectifs" },
  { french: "Chaud", wolof: "Tàng", phonetic: "tàng", category: "Marché & Adjectifs" },
  { french: "Fin / mince", wolof: "Sew", phonetic: "sew", category: "Marché & Adjectifs" },
  { french: "Long", wolof: "Gudd", phonetic: "goudd", category: "Marché & Adjectifs" },
  { french: "Court", wolof: "Gàtt", phonetic: "gàtt", category: "Marché & Adjectifs" },
  { french: "Profond", wolof: "Xóot", phonetic: "khoot", category: "Marché & Adjectifs" },
  { french: "Plein", wolof: "Fees", phonetic: "féés", category: "Marché & Adjectifs" },
  { french: "Vide", wolof: "Neen", phonetic: "néén", category: "Marché & Adjectifs" },
  { french: "Important", wolof: "Am solo", phonetic: "am solo", category: "Marché & Adjectifs" },
  { french: "Propre", wolof: "Set", phonetic: "set", category: "Marché & Adjectifs" },
  { french: "Sale", wolof: "Tilim", phonetic: "tilim", category: "Marché & Adjectifs" },
  { french: "Douloureux / difficile", wolof: "Metti", phonetic: "metti", category: "Marché & Adjectifs" },
  { french: "Faible", wolof: "Néew", phonetic: "néew", category: "Marché & Adjectifs" },
  { french: "Fort / puissant", wolof: "Doole", phonetic: "doole", category: "Marché & Adjectifs" },
  { french: "Large", wolof: "Yaatu", phonetic: "yaatou", category: "Marché & Adjectifs" },
  { french: "Nouveau", wolof: "Bees", phonetic: "béés", category: "Marché & Adjectifs" },
  { french: "Jour", wolof: "Bés", phonetic: "bés", category: "Temps" },
  { french: "Nuit", wolof: "Guddi", phonetic: "gouddi", category: "Temps" },
  { french: "Matin / demain", wolof: "Suba", phonetic: "souba", category: "Temps" },
  { french: "Après-midi / soir", wolof: "Ngoon", phonetic: "ngoon", category: "Temps" },
  { french: "Aujourd'hui", wolof: "Tay", phonetic: "tay", category: "Temps" },
  { french: "Hier", wolof: "Démb", phonetic: "démb", category: "Temps" },
  { french: "Demain", wolof: "Éllëg", phonetic: "élleug", category: "Temps" },
  { french: "Semaine", wolof: "Ayubés", phonetic: "ayoubés", category: "Temps" },
  { french: "Mois / lune", wolof: "Weer", phonetic: "wéér", category: "Temps" },
  { french: "Année", wolof: "At", phonetic: "at", category: "Temps" },
  { french: "Lundi", wolof: "Altine", phonetic: "altine", category: "Temps" },
  { french: "Mardi", wolof: "Talaata", phonetic: "talaata", category: "Temps" },
  { french: "Mercredi", wolof: "Àllarba", phonetic: "àllarba", category: "Temps" },
  { french: "Jeudi", wolof: "Alxamis", phonetic: "alkhamis", category: "Temps" },
  { french: "Vendredi", wolof: "Àjjuma", phonetic: "àdjdjouma", category: "Temps" },
  { french: "Samedi", wolof: "Gaawu", phonetic: "gaawou", category: "Temps" },
  { french: "Dimanche", wolof: "Dibéer", phonetic: "dibéer", category: "Temps" },
  { french: "Heure", wolof: "Waxtu", phonetic: "wakhtou", category: "Temps" },
  { french: "Moment / instant", wolof: "Simili", phonetic: "simili", category: "Temps" },
  { french: "Aube", wolof: "Njël", phonetic: "ndjeul", category: "Temps" },
  { french: "Midi", wolof: "Tisbaar", phonetic: "tisbaar", category: "Temps" },
  { french: "Crépuscule", wolof: "Timis", phonetic: "timis", category: "Temps" },
  { french: "Aurore", wolof: "Fajar", phonetic: "fadjar", category: "Temps" },
  { french: "Bientôt / dans peu de temps", wolof: "Ci kaw", phonetic: "tchi kaw", category: "Temps" },
  { french: "Maintenant", wolof: "Léegi", phonetic: "léegi", category: "Temps" },
  { french: "Il y a longtemps", wolof: "Bu yagg", phonetic: "bou yagg", category: "Temps" },
  { french: "Passer la nuit", wolof: "Fanaan", phonetic: "fanaan", category: "Temps" },
  { french: "Soleil", wolof: "Jant", phonetic: "djant", category: "Temps" },
  { french: "Étoile", wolof: "Bittéel", phonetic: "bittéel", category: "Temps" },
  { french: "Ciel", wolof: "Asamaan", phonetic: "asamaan", category: "Temps" },
  { french: "Pluie", wolof: "Taw", phonetic: "taw", category: "Temps" },
  { french: "Vent", wolof: "Ngelaw", phonetic: "ngelaw", category: "Temps" },
  { french: "Chaleur", wolof: "Naaj", phonetic: "naadj", category: "Temps" },
  { french: "Nuage", wolof: "Xur", phonetic: "khour", category: "Temps" },
  { french: "Lune", wolof: "Weer", phonetic: "wéér", category: "Nature" },
  { french: "Mer / océan", wolof: "Géej", phonetic: "géedj", category: "Nature" },
  { french: "Fleuve", wolof: "Dex", phonetic: "dekh", category: "Nature" },
  { french: "Champ", wolof: "Tool", phonetic: "tool", category: "Nature" },
  { french: "Arbre", wolof: "Garab", phonetic: "garab", category: "Nature" },
  { french: "Feuille", wolof: "Xob", phonetic: "khob", category: "Nature" },
  { french: "Terre / sol", wolof: "Tank", phonetic: "tank", category: "Nature" },
  { french: "Sable", wolof: "Bëñ-bëñ", phonetic: "beugn-beugn", category: "Nature" },
  { french: "Brousse / forêt", wolof: "Àll", phonetic: "àll", category: "Nature" },
  { french: "Colline", wolof: "Tund", phonetic: "tound", category: "Nature" },
  { french: "Fumée", wolof: "Saxaar", phonetic: "sakhaar", category: "Nature" },
  { french: "Feu", wolof: "Safara", phonetic: "safara", category: "Nature" },
  { french: "Pierre", wolof: "Doj", phonetic: "dodj", category: "Nature" },
  { french: "Rivage", wolof: "Palanteer", phonetic: "palantéér", category: "Nature" },
  { french: "Route / rue", wolof: "Mbedd", phonetic: "mbedd", category: "Nature" },
  { french: "Sol / terre (agricole)", wolof: "Suuf", phonetic: "souuf", category: "Nature" },
  { french: "Mouton", wolof: "Xar", phonetic: "khar", category: "Animaux" },
  { french: "Vache", wolof: "Bëy", phonetic: "beuy", category: "Animaux" },
  { french: "Âne", wolof: "Mbaam", phonetic: "mbaam", category: "Animaux" },
  { french: "Cheval", wolof: "Fas", phonetic: "fas", category: "Animaux" },
  { french: "Lion", wolof: "Gaynde", phonetic: "gaynde", category: "Animaux" },
  { french: "Chien", wolof: "Xaj", phonetic: "khadj", category: "Animaux" },
  { french: "Chat", wolof: "Muus", phonetic: "mouus", category: "Animaux" },
  { french: "Serpent", wolof: "Jaan", phonetic: "djaan", category: "Animaux" },
  { french: "Oiseau", wolof: "Picc", phonetic: "pitchtch", category: "Animaux" },
  { french: "Girafe", wolof: "Njool", phonetic: "ndjool", category: "Animaux" },
  { french: "Éléphant", wolof: "Ñay", phonetic: "gnay", category: "Animaux" },
  { french: "Hyène", wolof: "Waññ", phonetic: "wagngn", category: "Animaux" },
  { french: "Singe", wolof: "Golo", phonetic: "golo", category: "Animaux" },
  { french: "Bœuf / taureau", wolof: "Yëkk", phonetic: "yeukk", category: "Animaux" },
  { french: "Chèvre", wolof: "Bagas", phonetic: "bagas", category: "Animaux" },
  { french: "Lionne", wolof: "Ndey Gaynde", phonetic: "ndey gaynde", category: "Animaux" },
  { french: "Grenouille", wolof: "Xaaj", phonetic: "khaadj", category: "Animaux" },
  { french: "Moustique", wolof: "Njugup", phonetic: "ndjougoup", category: "Animaux" },
  { french: "Guêpe", wolof: "Sàng", phonetic: "sàng", category: "Animaux" },
  { french: "Ver", wolof: "Rëy", phonetic: "reuy", category: "Animaux" },
  { french: "Vautour", wolof: "Yiw", phonetic: "yiw", category: "Animaux" },
  { french: "Termite", wolof: "Buuñ", phonetic: "bouugn", category: "Animaux" },
  { french: "Poussin", wolof: "Pukka", phonetic: "poukka", category: "Animaux" },
  { french: "Hippopotame", wolof: "Gindi", phonetic: "gindi", category: "Animaux" },
  { french: "Vêtement", wolof: "Yéref", phonetic: "yéref", category: "Vêtements" },
  { french: "Boubou", wolof: "Mbubb", phonetic: "mboubb", category: "Vêtements" },
  { french: "Chemise", wolof: "Simis", phonetic: "simis", category: "Vêtements" },
  { french: "Pantalon", wolof: "Tubéy", phonetic: "toubéy", category: "Vêtements" },
  { french: "Chaussure", wolof: "Dàll", phonetic: "dàll", category: "Vêtements" },
  { french: "Ceinture", wolof: "Kerse", phonetic: "kerse", category: "Vêtements" },
  { french: "Caftan", wolof: "Kaftaan", phonetic: "kaftaan", category: "Vêtements" },
  { french: "Robe", wolof: "Fistaan", phonetic: "fistaan", category: "Vêtements" },
  { french: "Foulard / voile", wolof: "Musóor", phonetic: "mousoor", category: "Vêtements" },
  { french: "Chapeau", wolof: "Sagar", phonetic: "sagar", category: "Vêtements" },
  { french: "Pantalon bouffant traditionnel", wolof: "Sarwal", phonetic: "sarwal", category: "Vêtements" },
  { french: "Tissu", wolof: "Cere", phonetic: "tchere", category: "Vêtements" },
  { french: "Coton", wolof: "Dombax", phonetic: "dombakh", category: "Vêtements" },
  { french: "Bijou", wolof: "Ndagam", phonetic: "ndagam", category: "Vêtements" },
  { french: "Anneau / bague", wolof: "Weñ", phonetic: "wegn", category: "Vêtements" },
  { french: "Enseignant(e)", wolof: "Jàngalekat", phonetic: "djàngalekat", category: "Métiers" },
  { french: "Médecin / soignant", wolof: "Fajkat", phonetic: "fadjkat", category: "Métiers" },
  { french: "Travailleur(euse)", wolof: "Liggéeykat", phonetic: "liggéeykat", category: "Métiers" },
  { french: "Commerçant(e)", wolof: "Njaayaan", phonetic: "ndjaayaan", category: "Métiers" },
  { french: "Cultivateur / paysan", wolof: "Bàykat", phonetic: "bàykat", category: "Métiers" },
  { french: "Griot(te) / conteur", wolof: "Awo", phonetic: "awo", category: "Métiers" },
  { french: "Pêcheur", wolof: "Rëbbkat", phonetic: "reubbkat", category: "Métiers" },
  { french: "Chauffeur", wolof: "Wuude", phonetic: "wouude", category: "Métiers" },
  { french: "Docteur", wolof: "Doktoor", phonetic: "doktoor", category: "Métiers" },
  { french: "Soldat", wolof: "Xarekat", phonetic: "kharekat", category: "Métiers" },
  { french: "Sportif", wolof: "Yëngukat", phonetic: "yeungoukat", category: "Métiers" },
  { french: "Vendeur(se)", wolof: "Jaykat", phonetic: "djaykat", category: "Métiers" },
  { french: "Maçon", wolof: "Tabaxkat", phonetic: "tabakhkat", category: "Métiers" },
  { french: "Coiffeur(se)", wolof: "Sartkat", phonetic: "sartkat", category: "Métiers" },
  { french: "Musicien(ne)", wolof: "Musikkat", phonetic: "mousikkat", category: "Métiers" },
  { french: "Ville / village", wolof: "Dëkk", phonetic: "deukk", category: "Lieux" },
  { french: "Pays", wolof: "Réew", phonetic: "réew", category: "Lieux" },
  { french: "Rue", wolof: "Mbedd", phonetic: "mbedd", category: "Lieux" },
  { french: "École", wolof: "Jàngu", phonetic: "djàngou", category: "Lieux" },
  { french: "Mosquée", wolof: "Jaamu", phonetic: "djaamou", category: "Lieux" },
  { french: "Hôpital", wolof: "Lopitaan", phonetic: "lopitaan", category: "Lieux" },
  { french: "Pirogue / bateau", wolof: "Gaal", phonetic: "gaal", category: "Lieux" },
  { french: "Voiture", wolof: "Oto", phonetic: "oto", category: "Lieux" },
  { french: "Vélo (variante régionale)", wolof: "Sax", phonetic: "sakh", category: "Lieux" },
  { french: "Pont", wolof: "Poñ", phonetic: "pogn", category: "Lieux" },
  { french: "Chemin / route", wolof: "Yoon", phonetic: "yoon", category: "Lieux" },
  { french: "Aéroport", wolof: "Aeropoor", phonetic: "aeropoor", category: "Lieux" },
  { french: "Gare", wolof: "Gare", phonetic: "gare", category: "Lieux" },
  { french: "Cabinet médical", wolof: "Kër doktoor", phonetic: "keur doktoor", category: "Lieux" },
  { french: "À l'étranger", wolof: "Bitim réew", phonetic: "bitim réew", category: "Lieux" },
  { french: "En centre-ville", wolof: "Ci biir dëkk", phonetic: "tchi biir deukk", category: "Lieux" },
  { french: "Plage", wolof: "Tefes", phonetic: "tefes", category: "Lieux" },
  { french: "La mer", wolof: "Geej gi", phonetic: "géédj gi", category: "Lieux" },
  { french: "Milieu / centre", wolof: "Digg", phonetic: "digg", category: "Lieux" },
];

export type QuizQuestion = {
  id: number;
  lessonId: string;
  question: string;
  correct: string;
  choices: string[];
  direction: "fr-to-wo" | "wo-to-fr";
};

export function generateQuiz(lessonId: string, count = 10): QuizQuestion[] {
  const lesson = lessons.find((l) => l.id === lessonId);
  if (!lesson) return [];
  const words = [...lesson.words];
  const shuffled = words.sort(() => Math.random() - 0.5).slice(0, count);

  return shuffled.map((word, i) => {
    const direction: "fr-to-wo" | "wo-to-fr" = Math.random() > 0.5 ? "fr-to-wo" : "wo-to-fr";
    const correct = direction === "fr-to-wo" ? word.wolof : word.french;
    const question = direction === "fr-to-wo" ? word.french : word.wolof;

    const otherWords = words.filter((w) => w !== word);
    const wrongAnswers = otherWords
      .sort(() => Math.random() - 0.5)
      .slice(0, 3)
      .map((w) => (direction === "fr-to-wo" ? w.wolof : w.french));

    const choices = [correct, ...wrongAnswers].sort(() => Math.random() - 0.5);

    return {
      id: i,
      lessonId,
      question,
      correct,
      choices,
      direction,
    };
  });
}

// Retourne un mot différent chaque jour, choisi de façon déterministe
// à partir de la date du jour (le même mot toute la journée pour tout le monde).
export function getWordOfTheDay(): DictionaryEntry {
  const start = new Date(2026, 0, 1).getTime();
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  const dayIndex = Math.floor((today - start) / (1000 * 60 * 60 * 24));
  const index = ((dayIndex % dictionary.length) + dictionary.length) % dictionary.length;
  return dictionary[index];
}
